spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tasks_database
  application:
    name: task-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    hostname: localhost